<h1>SchemaTool</h1>

<div class="nette-inner">
	<div id="nette-debug-schema-tool-status"></div>
	
	<table>
		<tr>
			<th>Create</th>
			<td><input type="submit" value="Execute" class="nette-debug-schema-tool-ajax" name="create"></td>
		</tr>
		<tr>
			<th>Update</th>
			<td><input type="submit" value="Execute" class="nette-debug-schema-tool-ajax" name="update"></td>
		</tr>
		<tr>
			<th>Drop</th>
			<td><input type="submit" value="Execute" class="nette-debug-schema-tool-ajax" name="drop"></td>
		</tr>
	</table>
</div>

<style type="text/css">
#nette-debug-schema-tool {
	width: 100%;
}

#nette-debug-schema-tool input {
	padding: 2px;
	background: #eee;
	border: 1px solid #ccc;
}

#nette-debug-schema-tool input:hover {
	background: #666;
	color: #fff;
	border: 1px solid #444;
}

#nette-debug-schema-tool .success {
	background: #A3F06C;
	border: 1px solid #5FA92A;
	padding: 1em;
	margin-bottom: 5px;
}

#nette-debug-schema-tool .error {
	background: #FAD3C4;
	border: 1px solid #D4C4C9;
	padding: 1em;
	margin-bottom: 5px;
}
</style>

<script type="text/javascript">
/* <![CDATA[ */

(function(){

	var $ = Nette.Q.factory;

	var schemaPanel = {
		init: function () {
			$('.nette-debug-schema-tool-ajax').bind('click', function (e) {
				schemaPanel.commit(this.name);
			})
		},

		commit: function (cmd) {

			var xmlHttp = window.ActiveXObject ? new ActiveXObject('Microsoft.XMLHTTP') : new XMLHttpRequest();
			xmlHttp.onreadystatechange = function() {
				if (xmlHttp.readyState == 4) {

					var status = $('#nette-debug-schema-tool-status').dom();

					if (xmlHttp.status == 200) {
						message = JSON.parse(xmlHttp.responseText);

						status.innerHTML = message.text;
						status.className = message.cls;
					} else {
						status.innerHTML = 'Unhandled exception';
						status.className = 'error';
					}
				}
			}
			xmlHttp.open("POST", <?php echo json_encode(\Nette\Environment::getApplication()->getPresenter()->link('this')); ?>, true);
			xmlHttp.setRequestHeader('X-Schema-Client', 'devel');
			xmlHttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
			xmlHttp.send(cmd);
		}
	}


	schemaPanel.init();

})();

/* ]]> */
</script>